version: '3'

services:
  postgres:
    container_name: my-postgres-container
    build: 
      context: ./dockerFiles
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: Snusmumric
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /D/AppsInfo/DataSerializer/TempInfo/DatabaseInfo
    restart: unless-stopped
    mem_limit: 0.5g 
    cpus: 0.5

networks:
  postgres:
    driver: bridge