FROM postgres
ENV POSTGRES_USER=Snusmumric
ENV POSTGRES_PASSWORD=admin
RUN mkdir -p /S/AppsInfo/DataSerializer/PostgreContainer
RUN chown -R postgres:postgres /S/AppsInfo/DataSerializer/PostgreContainer
ENV PGDATA /S/AppsInfo/DataSerializer/PostgreContainer
ENV TZ=Europe/Moscow
EXPOSE 5432
CMD ["postgres"]
