FROM postgres
ENV POSTGRES_USER=Snusmumric
ENV POSTGRES_PASSWORD=admin
RUN mkdir -p /D/AppsInfo/DataSerializer/PostgreContainer
RUN chown -R postgres:postgres /D/AppsInfo/DataSerializer/PostgreContainer
ENV PGDATA /D/AppsInfo/DataSerializer/PostgreContainer
ENV TZ=Europe/Moscow
EXPOSE 5432
CMD ["postgres"]
